"""Constants for Raven House Tools quiz support."""

DOMAIN = "raven_house_tools"

PREFIX_QUIZ = "rh_quiz"
STORAGE_VERSION = 1

ATTR_PLAYER_NAME = "player_name"
ATTR_PLAYER_ALIAS = "player_alias"
ATTR_PLAYER_PHOTO = "player_photo"
ATTR_TOTAL_SCORE = "total_score"
ATTR_ROUND_SCORE = "current_round_score"
ATTR_LAST_ROUND_SCORE = "last_round_score"
ATTR_PLAYER_ENABLED = "enabled"
ATTR_PLAYER_ID = "player_id"
ATTR_PLAYER_METRIC = "player_metric"
ATTR_CREATED = "created"
ATTR_QUIZ_ROUNDS = "quiz_rounds"
ATTR_ACTIVE_ROUND_INDEX = "active_round_index"
ATTR_ACTIVE_ROUND_NAME = "active_round_name"
ATTR_ROUND_POSITION_INDEX = "round_position_index"
ATTR_TOTAL_ROUNDS = "total_rounds"

SERVICE_ADD_PLAYER = "add_player"
SERVICE_REMOVE_PLAYER = "remove_player"
SERVICE_ENABLE_PLAYER = "enable_player"
SERVICE_DISABLE_PLAYER = "disable_player"
SERVICE_RENAME_PLAYER = "rename_player"
SERVICE_UPDATE_PLAYER_ALIAS = "update_player_alias"
SERVICE_UPDATE_PLAYER_PHOTO = "update_player_photo"
SERVICE_RESET_PLAYER_SCORE = "reset_player_score"
SERVICE_ADD_POINTS = "add_points"
SERVICE_REMOVE_POINTS = "remove_points"
SERVICE_USE_JOKER = "use_joker"
SERVICE_START_NEW_ROUND = "start_new_round"
SERVICE_START_ROUND = "start_round"
SERVICE_END_ROUND = "end_round"
SERVICE_START_NEW_QUIZ = "start_new_quiz"
SERVICE_RESET_QUIZ = "reset_quiz"
SERVICE_SET_QUIZ_ROUNDS = "set_quiz_rounds"

QUIZ_SIGNAL_UPDATE = f"{DOMAIN}_player_update"
